[package]
name = "memorydb"
version = "0.2.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "in-memory implementation of hashdb"
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
heapsize = "0.4"
hashdb = { path = "../hashdb" }
plain_hasher = { path = "../plain_hasher" }
rlp = { path = "../rlp", default-features = false }

[dev-dependencies]
tiny-keccak = "1.4.2"
ethereum-types = "0.3"
keccak-hasher = { path = "../test-support/keccak-hasher" }
keccak-hash = { path = "../keccak-hash" }