[workspace]
members = [
	"fixed-hash",
	"keccak-hash",
	"kvdb",
	"kvdb-memorydb",
	"kvdb-rocksdb",
	"parity-bytes",
	"parity-crypto",
	"parity-path",
	"plain_hasher",
	"rlp",
	"transaction-pool",
	"trace-time",
	"trie-standardmap",
	"triehash",
	"uint",
	"parity-util-mem",
	"primitive-types",
	"ethereum-types",
	"ethbloom",
]

# TODO: remove after https://github.com/paritytech/rust-rocksdb/pull/31 merges and changes are published
[patch.crates-io]
parity-rocksdb = { git = "https://github.com/paritytech/rust-rocksdb/", branch = "dp/add-property-getters" }
